name: Automerge Dependabot requests

on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.MERGE_PAT_TOKEN }}